function generateProtocolList(subjectName,gridType,expDates,protocolNames,stimType,comments,listType)

% check list for sanity
if checkListSanity(expDates,protocolNames,stimType)
    throw(MException([mfilename ':paramsError'], ...
        'Parameters incorrect or not in proper form'));
end

switch listType
    case 'db'
        generateProtocolListDB(subjectName,gridType,expDates,protocolNames,stimType,comments);
    case 'm'
        generateProtocolListM(subjectName,gridType,expDates,protocolNames,stimType,comments);
    otherwise
        throw(MException([mfilename ':unknownListType'], ...
            'Unrecognized list type'));
end

end

function generateProtocolListDB(subjectName,gridType,expDates,protocolNames,stimType,comments)

throw(MException([mfilename ':notImplemented'], ...
    'This functionality is not yet implemented'));

end

function generateProtocolListM(subjectName,gridType,expDates,protocolNames,stimTypes,comments)

% get protocol list path
[protocolListFileName,protocolListPath] = getProtocolListPath(subjectName,gridType);

% open text file for writing, in the same folder as the binary file
[~,fileNameM,~] = fileparts(protocolListFileName);
filePathM = fullfile(protocolListPath,[fileNameM '.m']);
[fidM,errMsg] = fopen(filePathM,'w');
if fidM == -1
    throw(MException([mfilename ':fileError'], errMsg));
end

% write the header
fprintf(fidM,'%% Automagically generated by %s() at %s\n',mfilename,datestr(now));
fprintf(fidM,'%%\n');
fprintf(fidM,'%% This is the human-readable form of %s\n',protocolListFileName);
fprintf(fidM,'%% (.) Do NOT modify this file by hand. Use updateProtocolList() instead.\n');
fprintf(fidM,'%% (.) Do NOT call/run this file directly. Use getAllProtocols() instead.\n\n');
fprintf(fidM,'function [expDates,protocolNames,stimType] = %s\n\n',fileNameM);

% write an error (warning?) not to use this file directly
fprintf(fidM,['error(''Do not call/run this file directly. ' ...
    'Use getAllProtocols(''''' subjectName ''''',''''' gridType ''''') instead.'');\n']);

lastDateString = '';
h = waitbar(1,'Saved 0 protocol(s)','Name','Generating human-readable protocol list...');
for i=1:length(expDates)
    % add current entry
    if ~strcmp(lastDateString,expDates{i})
        fprintf(fidM,'\n'); % leave a blank line between two days of recording
        lastDateString = expDates{i};
    end
    fprintf(fidM,['expDates{' num2str(i) '} = ''' expDates{i} ...
        '''; protocolNames{' num2str(i) '} = ''' protocolNames{i} ...
        '''; stimType{' num2str(i) '} = ' num2str(stimTypes{i}) ';']);
    if ~isempty(comments{i})
        comments{i} = strrep(comments{i},'%','%%'); % avoid interpretation as format spec
        comments{i} = strrep(comments{i},'\','\\'); % avoid interpretation as control char
        fprintf(fidM,[' %% ' comments{i}]);
    end
    fprintf(fidM,'\n');
    
    waitbar(1,h,['Saved ' num2str(i) ' protocol(s)']);
end

fprintf(fidM,'\nend\n');
fclose(fidM);
close(h);

end
